// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.4
// source: google/plugin/interceptor.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodHandler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"` // login token
	Whitelist     string `protobuf:"bytes,2,opt,name=whitelist,proto3" json:"whitelist,omitempty"`         // ip whitelist
	Logger        bool   `protobuf:"varint,3,opt,name=logger,proto3" json:"logger,omitempty"`              // logger
}

func (x *MethodHandler) Reset() {
	*x = MethodHandler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_plugin_interceptor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodHandler) ProtoMessage() {}

func (x *MethodHandler) ProtoReflect() protoreflect.Message {
	mi := &file_google_plugin_interceptor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodHandler.ProtoReflect.Descriptor instead.
func (*MethodHandler) Descriptor() ([]byte, []int) {
	return file_google_plugin_interceptor_proto_rawDescGZIP(), []int{0}
}

func (x *MethodHandler) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *MethodHandler) GetWhitelist() string {
	if x != nil {
		return x.Whitelist
	}
	return ""
}

func (x *MethodHandler) GetLogger() bool {
	if x != nil {
		return x.Logger
	}
	return false
}

type ServiceHandler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"` // login token
	Whitelist     string `protobuf:"bytes,2,opt,name=whitelist,proto3" json:"whitelist,omitempty"`         // ip whitelist
	Logger        bool   `protobuf:"varint,3,opt,name=logger,proto3" json:"logger,omitempty"`              // logger
}

func (x *ServiceHandler) Reset() {
	*x = ServiceHandler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_plugin_interceptor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHandler) ProtoMessage() {}

func (x *ServiceHandler) ProtoReflect() protoreflect.Message {
	mi := &file_google_plugin_interceptor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHandler.ProtoReflect.Descriptor instead.
func (*ServiceHandler) Descriptor() ([]byte, []int) {
	return file_google_plugin_interceptor_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceHandler) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *ServiceHandler) GetWhitelist() string {
	if x != nil {
		return x.Whitelist
	}
	return ""
}

func (x *ServiceHandler) GetLogger() bool {
	if x != nil {
		return x.Logger
	}
	return false
}

var file_google_plugin_interceptor_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodHandler)(nil),
		Field:         63500,
		Name:          "google.plugin.method_handler",
		Tag:           "bytes,63500,opt,name=method_handler",
		Filename:      "google/plugin/interceptor.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceHandler)(nil),
		Field:         63501,
		Name:          "google.plugin.service_handler",
		Tag:           "bytes,63501,opt,name=service_handler",
		Filename:      "google/plugin/interceptor.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional google.plugin.MethodHandler method_handler = 63500;
	E_MethodHandler = &file_google_plugin_interceptor_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional google.plugin.ServiceHandler service_handler = 63501;
	E_ServiceHandler = &file_google_plugin_interceptor_proto_extTypes[1]
)

var File_google_plugin_interceptor_proto protoreflect.FileDescriptor

var file_google_plugin_interceptor_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x68, 0x69,
	0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x68,
	0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x67, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x22,
	0x6c, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x68, 0x69, 0x74, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x68, 0x69, 0x74,
	0x65, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x3a, 0x65, 0x0a,
	0x0e, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12,
	0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x8c, 0xf0, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x0d, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x3a, 0x69, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x8d, 0xf0, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52,
	0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x42,
	0x14, 0x5a, 0x12, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_plugin_interceptor_proto_rawDescOnce sync.Once
	file_google_plugin_interceptor_proto_rawDescData = file_google_plugin_interceptor_proto_rawDesc
)

func file_google_plugin_interceptor_proto_rawDescGZIP() []byte {
	file_google_plugin_interceptor_proto_rawDescOnce.Do(func() {
		file_google_plugin_interceptor_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_plugin_interceptor_proto_rawDescData)
	})
	return file_google_plugin_interceptor_proto_rawDescData
}

var file_google_plugin_interceptor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_plugin_interceptor_proto_goTypes = []interface{}{
	(*MethodHandler)(nil),               // 0: google.plugin.MethodHandler
	(*ServiceHandler)(nil),              // 1: google.plugin.ServiceHandler
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
}
var file_google_plugin_interceptor_proto_depIdxs = []int32{
	2, // 0: google.plugin.method_handler:extendee -> google.protobuf.MethodOptions
	3, // 1: google.plugin.service_handler:extendee -> google.protobuf.ServiceOptions
	0, // 2: google.plugin.method_handler:type_name -> google.plugin.MethodHandler
	1, // 3: google.plugin.service_handler:type_name -> google.plugin.ServiceHandler
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_plugin_interceptor_proto_init() }
func file_google_plugin_interceptor_proto_init() {
	if File_google_plugin_interceptor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_plugin_interceptor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodHandler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_plugin_interceptor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceHandler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_plugin_interceptor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_google_plugin_interceptor_proto_goTypes,
		DependencyIndexes: file_google_plugin_interceptor_proto_depIdxs,
		MessageInfos:      file_google_plugin_interceptor_proto_msgTypes,
		ExtensionInfos:    file_google_plugin_interceptor_proto_extTypes,
	}.Build()
	File_google_plugin_interceptor_proto = out.File
	file_google_plugin_interceptor_proto_rawDesc = nil
	file_google_plugin_interceptor_proto_goTypes = nil
	file_google_plugin_interceptor_proto_depIdxs = nil
}
